version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /test/ssh-server
    schedule:
      interval: daily
